### ISSUE TITLE
Transparent Black Bars

### ISSUE THREAD

**Issue by Nadekai** [Unjust-Harry/FancyScreenPatchForRecettear#2]
Getting transparent bars on the sides.

![recettear_9ntNmkg6j7](https://github.com/Unjust-Harry/FancyScreenPatchForRecettear/assets/89274692/39628423-62fc-420f-8175-26ad1528f0bd)

**Comment by just-harry** [comment]
Hi Nadekai, thanks for the bug report.
I think I know the cause of this, but I don't know which resolutions it happens with.

Could you tell me what resolution you had the game set to run at, when you took this screenshot, please?

**Comment by Nadekai** [comment]
On 1440p 165hz.

**Comment by just-harry** [comment]
Thanks again for the report. The bug here was that the texture-filtering algorithm option for `FPSOSD` was also, wrongly, applying to the pillarboxes drawn by the patch.

I've released [version 1.0.1](https://github.com/Unjust-Harry/FancyScreenPatchForRecettear/releases/tag/v1.0.1) of the patch, which should fix the issue.

**Comment by Nadekai** [comment]
Thanks!
